<a href="https://colab.research.google.com/github/Axerawd/Feature-Engineering_W5/blob/main/Exercise_W5_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# *Exercise 5 Feature Engineering*

Anggota Kelompok:

Muhammad Fathur Rossi (25031554026)

Thessalonica Alexandra Dominic R.T. (25031554084)

Data yang di kerjakan dari hasil **Exercise 4**:


1.   **API Preprocessing**

In [17]:
!pip install gensim

Requirement already satisfied: gensim in /usr/local/lib/python3.13/dist-packages (4.4.0)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.13/dist-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.13/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.13/dist-packages (from gensim) (8.0.2)
Requirement already satisfied: wrapt in /usr/local/lib/python3.13/dist-packages (from smart_open>=1.8.1->gensim) (2.5.0)

In [18]:
!pip install umap-learn

Requirement already satisfied: umap-learn in /usr/local/lib/python3.13/dist-packages (0.5.12)
Requirement already satisfied: numpy>=1.23 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (2.1.3)
Requirement already satisfied: scipy>=1.3.1 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (1.16.3)
Requirement already satisfied: scikit-learn>=1.6 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (1.6.1)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (0.61.2)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.13/dist-packages (from umap-learn) (0.6.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from umap-learn) (4.67.3)
Requirement already satisfied: llvmlite<0.45,>=0.44.0dev0 in /usr/local/lib/python3.13/dist-packages (from numba>=0.51.2->umap-learn) (0.44.0)
Requirement already satisfied: joblib>=0.11 in /usr/local/lib/python3.13/dist-packages (from pynndescent>=0.5->umap-learn) (1.6.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn>=1.6->umap-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib>=0.11->pynndescent>=0.5->umap-learn) (3.1.2)

In [19]:
import pandas as pd
import warnings
import gensim.models
import numpy as np
import nltk
import plotly.express as px
from umap import UMAP
from nltk import word_tokenize
from tqdm import tqdm
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

print ("berhasil mengimport library")

berhasil mengimport library

In [20]:
warnings.filterwarnings(action='ignore')
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [21]:
df = pd.read_csv('hasil_preprocessing_youtube.csv')
df = df.dropna().reset_index().drop(columns=['index'])
df_pre = df['comment']
df_pre.info()

<class 'pandas.core.series.Series'>
RangeIndex: 3264 entries, 0 to 3263
Series name: comment
Non-Null Count  Dtype
--------------  -----
3264 non-null   object
dtypes: object(1)
memory usage: 25.6+ KB

In [22]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df_pre)
df_FE = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
df_FE

,00,000,01,02,03,04,05,05betul,05justru,05lah,...,𝗶𝗻𝗶,𝗸𝗶𝘁𝗮,𝗺𝗮𝗻𝘂𝘀𝗶𝗮,𝘀𝗲𝗯𝗮𝗴𝗮𝗶,𝘀𝗲𝗺𝗲𝘀𝘁𝗮,𝘀𝗶𝗻𝗴𝗸𝗮𝘁,𝘂𝗻𝘁𝘂𝗸,𝘄𝗮𝗸𝘁𝘂,𝘄𝗮𝗹𝗮𝘂𝗽𝘂𝗻,𝘆𝗴
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3259,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3260,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3261,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3262,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3263,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [23]:
sentences = [word_tokenize(tweet.lower()) for tweet in tqdm(df_pre)]
sentences

100%|██████████| 3264/3264 [00:00<00:00, 4460.50it/s]

[['dalam',
  'video',
  'ini',
  'mungkin',
  'kalian',
  'menyadari',
  'bahwa',
  'bagian',
  'tentang',
  'evolusi',
  'manusia',
  'tidak',
  'saya',
  'bahas',
  'secara',
  'mendalam',
  '.',
  'ini',
  'bukan',
  'karena',
  'topik',
  'tersebut',
  'tidak',
  'penting',
  '.',
  'justru',
  'sebaliknya',
  ',',
  'evolusi',
  'manusia',
  'adalah',
  'bagian',
  'krusial',
  'dalam',
  'kisah',
  'panjang',
  'bumi',
  'dan',
  'kehidupan',
  '.',
  'namun',
  'saya',
  'menyadari',
  'bahwa',
  'di',
  'indonesia',
  ',',
  'topik',
  'evolusi',
  'masih',
  'menjadi',
  'isu',
  'yang',
  'cukup',
  'sensitif',
  ',',
  'terutama',
  'jika',
  'tidak',
  'dijelaskan',
  'dengan',
  'hati-hati',
  'dan',
  'konteks',
  'yang',
  'tepat',
  '.',
  'banyak',
  'orang',
  'mengira',
  'bahwa',
  'teori',
  'evolusi',
  'menyatakan',
  'manusia',
  'berasal',
  'dari',
  'kera',
  'atau',
  'monyet',
  '.',
  'padahal',
  ',',
  'itu',
  'adalah',
  'sebuah',
  'miskonsepsi',
  'besar',
  '.',
  'faktanya',
  'charles',
  'darwin',
  'tidak',
  'pernah',
  'mengatakan',
  'bahwa',
  'manusia',
  'berasal',
  'dari',
  'kera',
  '.',
  'yang',
  'ia',
  'dan',
  'para',
  'ilmuwan',
  'evolusi',
  'kemukakan',
  'adalah',
  'bahwa',
  'manusia',
  'dan',
  'kera',
  'modern',
  '(',
  'seperti',
  'simpanse',
  'dan',
  'gorila',
  ')',
  'memiliki',
  'nenek',
  'moyang',
  'bersama',
  'yang',
  'hidup',
  'jutaan',
  'tahun',
  'yang',
  'lalu',
  '.',
  'jadi',
  'bukan',
  'berarti',
  'manusia',
  'berubah',
  'menjadi',
  'kera',
  'atau',
  'sebaliknya',
  '.',
  'kita',
  'semua',
  'adalah',
  'bagian',
  'dari',
  'satu',
  'garis',
  'evolusi',
  'yang',
  'berbeda',
  'namun',
  'memiliki',
  'asal-usul',
  'yang',
  'sama',
  'jauh',
  'di',
  'masa',
  'lalu',
  '.',
  'saya',
  'memilih',
  'untuk',
  'tidak',
  'membahasnya',
  'secara',
  'rinci',
  'dalam',
  'video',
  'karena',
  ':',
  '-',
  'fokus',
  'utama',
  'video',
  'ini',
  'adalah',
  'untuk',
  'menggambarkan',
  'bagaimana',
  'bumi',
  'terbentuk',
  ',',
  'berkembang',
  ',',
  'hingga',
  'menjadi',
  'rumah',
  'bagi',
  'kehidupan',
  'yang',
  'kita',
  'kenal',
  'sekarang',
  ',',
  'bukan',
  'untuk',
  'mengupas',
  'semua',
  'aspek',
  'biologi',
  'manusia',
  '.',
  '-',
  'topik',
  'evolusi',
  'manusia',
  'membutuhkan',
  'penjelasan',
  'yang',
  'lebih',
  'luas',
  ',',
  'sabar',
  ',',
  'dan',
  'netral',
  ',',
  'agar',
  'tidak',
  'menimbulkan',
  'kesalahpahaman',
  'baru',
  '.',
  '-',
  'saya',
  'ingin',
  'penonton',
  'dari',
  'berbagai',
  'latar',
  'belakang',
  'tetap',
  'merasa',
  'nyaman',
  'saat',
  'menyimak',
  'video',
  ',',
  'sambil',
  'tetap',
  'membuka',
  'ruang',
  'diskusi',
  'ilmiah',
  'yang',
  'sehat',
  '.',
  'namun',
  'satu',
  'hal',
  'yang',
  'perlu',
  'ditegaskan',
  ':',
  'memahami',
  'teori',
  'evolusi',
  'bukan',
  'berarti',
  'menolak',
  'kepercayaan',
  '.',
  'banyak',
  'ilmuwan',
  'dari',
  'berbagai',
  'agama',
  'yang',
  'menerima',
  'fakta-fakta',
  'ilmiah',
  'ini',
  'sebagai',
  'bagian',
  'dari',
  'cara',
  'tuhan',
  'bekerja',
  'melalui',
  'alam',
  '.',
  'semoga',
  'dengan',
  'pemahaman',
  'yang',
  'lebih',
  'jernih',
  ',',
  'kita',
  'bisa',
  'melihat',
  'bahwa',
  'ilmu',
  'pengetahuan',
  'bukan',
  'untuk',
  'menentang',
  'keyakinan',
  ',',
  'tapi',
  'untuk',
  'memahami',
  'dunia',
  'ini',
  'dengan',
  'lebih',
  'dalam',
  'dan',
  'penuh',
  'rasa',
  'ingin',
  'tahu',
  '.'],
 ['kocak',
  '....',
  'cerita',
  'seblm',
  'tidur',
  '....',
  'ceritain',
  'kisah',
  'nabi',
  'adam',
  'dan',
  'siti',
  'hawa',
  '...'],
 ['\u200b',
  '@',
  'andryantz_story',
  'bagus',
  'untuk',
  'dipelajari',
  'tp',
  'jangan',
  'sampai',
  'menafikan',
  'ilmu',
  'pengetahuan',
  '.'],
 ['\u200b',
  '@',
  'andryantz_storytunjukan',
  'dengan',
  'ilmu',
  'pengetahuan',
  'anda',
  'jangan',
  'hanya',
  'komen',
  'seolah',
  'menyepelekan',
  'karya',
  'orang',
  '.',
  'kalo',
  'hanya',
  'komen',
  'anak',
  'tk',
  'udah',
  'bisa',
  'komen'],
 ['18:50',
  'dia',
  'sedang',
  'berkaca',
  ',',
  'mengagumi',
  'dirinya',
  'sendiri',
  'melalui',
  'manusia',
  '.',
  'saya',
  'seorang',
  'manusia',
  'yang',
  'memiliki',
  'nilai',
  ',',
  'bertenya-tanya',
  'dengan',
  'heran',
  ',',
  'rasa',
  'kagum',
  'tak',
  'ternalar',
  'atas',
  'keajaiban',
  'dunia',
  'ini',
  '.',
  'darimanakah',
  'kesadaran',
  'ini',
  '?',
  'mengapa',
  'alam',
  'semesta',
  'ini',
  'ingin',
  'ada',
  '?'],
 ['kalo', 'manusia', 'dari', 'kera', 'kenapa', 'masih', 'ada', 'kera', '?'],
 ['coba',
  'buat',
  'kolam',
  'agak',
  'luas',
  ',',
  'tiba2',
  'muncul',
  'ikan',
  ',',
  'gk',
  'tahu',
  'dari',
  'mana',
  'asalnya',
  ','],
 ['jika',
  'supernova/',
  'big',
  'bang',
  'adalah',
  'awal',
  'mula',
  'permulaan',
  'dari',
  'sebuah',
  'kehidupan',
  'lantas',
  'apa',
  'yang',
  'ada',
  'sebelum',
  'peristiwa',
  'ini',
  'apakah',
  'ada',
  'kehidupan',
  'di',
  'sekitar',
  'bintang',
  'ini',
  'apakah',
  'ada',
  'makhluk',
  'hidup',
  'sebelum',
  'era',
  'kita',
  '?'],
 ['manusia',
  'diturunkan',
  'dari',
  'syurga',
  'yh',
  'brada',
  'di',
  'atas',
  'langit',
  'la',
  'admin',
  '..',
  'bukan',
  'terhasil',
  'dari',
  'abu2',
  'ledakan',
  '...',
  'semua',
  'diciptakan',
  'oleh',
  'allah',
  's.w.t',
  '...',
  'ini',
  'faktanya'],
 ['maha',
  'besar',
  'allah',
  'dengan',
  'segala',
  'kuasanya',
  '.',
  'semua',
  'terjadi',
  'karena',
  'kuasa',
  'dan',
  'izin',
  'nya',
  '.',
  'allah',
  'bisa',
  '``',
  'mematikan',
  "''",
  'dan',
  '``',
  'menghidupkan',
  "''",
  'semua',
  'alam',
  'semesta',
  'ini',
  '..'],
 ['cerita',
  'spanjang',
  'ini',
  'siapa',
  'yg',
  'tau',
  'peristiwanya',
  'yah',
  ',',
  'info',
  'nya',
  'dr',
  'mana',
  'sih',
  '..'],
 ['jadi', 'kiamat', 'awal', 'dari', 'peradapan', 'baru', 'ya', '?'],
 ['kemajuan',
  'ilmu',
  'pengetahuan',
  'semakin',
  'lama',
  'semakin',
  'bersimpangan',
  'dgn',
  'dogma2',
  'agama',
  '....',
  '🤔'],
 ['bukan', 'kocak', 'itu', 'biasa', 'bumi', 'ya😊'],
 ['lebih',
  'ngeri',
  'manusia',
  'yang',
  'merusak',
  'bumi',
  'itu',
  'sendiri',
  'bang'],
 ['banyak', 'banget', 'iklannya'],
 ['bg', 'sumber', 'literasi', 'nya', 'ini', 'dari', 'mana', '?'],
 ['vidio', 'seputar', 'exoplanet', 'di', 'galaksi', 'andromeda'],
 ['yg',
  'sllu',
  'gw',
  'bertanya',
  'tanya',
  'knp',
  'ahli',
  'bilang',
  '4,5',
  'miliyar',
  'knp',
  'gak',
  '5',
  'miliyar',
  'knp',
  'gk',
  '3',
  'milyar'],
 ['cerita', 'bagus'],
 ['masih',
  'bingung',
  'sy',
  '...',
  'kok',
  'manusia',
  'bisa',
  'memprediksi',
  'gmna',
  'terbentuk',
  'nya',
  'bumi',
  '...',
  'cuma',
  'mengandalkan',
  'technology',
  '...',
  'apa',
  'iya',
  'terjadi',
  'nya',
  'seperti',
  'di',
  'video',
  '...',
  'dah',
  'lah',
  'ngikut',
  'ja',
  '..',
  '😂😂😂'],
 ['masih',
  'banyak',
  'kaum',
  'yg',
  'menganggap',
  'bumi',
  'ini',
  'datar',
  '.',
  'kaum',
  'fe',
  'namanya'],
 ['takut', 'banget', 'suatu', 'saat', 'bumi', 'kembali', 'hening', 'lagi'],
 ['ya', 'bodo', 'amat', 'sih', ',', 'suatu', 'saat', 'kita', 'mati', 'kok😂'],
 ['klw',
  'melihat',
  'dn',
  'memperhatikan',
  'akan',
  'semesta',
  'ternyata',
  'bumi',
  'hanyalah',
  'butiran',
  'debu',
  '...',
  '!',
  '!',
  '!',
  'palagi',
  'hanya',
  'manusia',
  '...',
  '?',
  '?',
  '?',
  'jd',
  'apa',
  'yg',
  'disombongkan',
  'manusia',
  '...',
  '?',
  '?',
  '?',
  'sungguh',
  'mahluk',
  'yg',
  'sangat',
  'lemah',
  '...',
  '!',
  '!',
  '!'],
 ['masyaallah'],
 ['coba',
  'jelaskan',
  'secara',
  'detail',
  'bagaimana',
  'makhluk',
  'hidup',
  'muncul',
  'di',
  'dunia',
  'ini',
  'dari',
  'awal',
  'sampai',
  'terbentuk',
  'jangan',
  'hanya',
  'sebut',
  'zaman',
  'menurut',
  'prasejarah',
  'dan',
  'video',
  'serta',
  'penjelasan',
  'yang',
  'di',
  'berikan',
  'tiba',
  "''",
  'sudah',
  'terbentuk',
  'sempurna',
  '.....',
  'ini',
  'video',
  'pembodohan'],
 ['benar',
  'firman',
  'alloh',
  'swt',
  'bumi',
  'dan',
  'langit',
  'dulunya',
  'satu',
  'padu',
  'kemudian',
  'alloh',
  'swt',
  'memisahkan',
  'nya',
  '.',
  'qs',
  'al',
  'anbiya',
  "'",
  '30',
  '.',
  'dan',
  'alloh',
  'swt',
  'menciptakan',
  'makhluk',
  'hidup',
  'dari',
  'air',
  '.',
  '.',
  'dan',
  'alloh',
  'swt',
  'menciptakan',
  'manusia',
  'untuk',
  'hidup',
  'di',
  'bumi',
  'untuk',
  'beribadah',
  'kepada',
  'alloh',
  'swt',
  'yang',
  'maha',
  'kuasa',
  ',',
  'maha',
  'esa',
  'yang',
  'tidak',
  'ada',
  'sekutu',
  'bagi',
  'nya',
  '..',
  'besok',
  'alloh',
  'swt',
  'hancurkan',
  'bumi.',
  ',',
  'kiamat',
  '.',
  'apabila',
  'air',
  'laut',
  'dipanaskan',
  'qs',
  'at',
  'takwir',
  '.',
  'dan',
  'apabila',
  'air',
  'laut',
  'dijadikan',
  'meluap',
  'qs',
  'al',
  'infithor',
  '.',
  'bukankah',
  'perubahan',
  'iklim',
  'saat',
  'ini',
  'menjadikan',
  'air',
  'laut',
  'panas',
  'dan',
  'perlahan-lahan',
  'air',
  'laut',
  'naik',
  '.',
  'wes',
  'gek',
  'kiamat',
  'aja',
  ',',
  'manusia',
  'hidup',
  'di',
  'bumi',
  'tapi',
  'lupa',
  'pada',
  'alloh',
  'swt',
  'yang',
  'menciptakan',
  'bumi',
  ',',
  'manusia',
  'bersenang',
  'senang',
  'diatas',
  'bumi',
  'besok',
  'akan',
  'menangis',
  'di',
  'perut',
  'bumi',
  '.',
  'bukankah',
  'rusaknya',
  'bumi',
  'karena',
  'dampak',
  'kemajuan',
  'sains',
  'dan',
  'teknologi',
  '.'],
 ['bacod'],
 ['manusia',
  'ini',
  'debu',
  'kecil',
  'tapi',
  'ko',
  'ada',
  'manusia',
  'sombong',
  'yang',
  'suka',
  'mengusir',
  'manusia',
  'lainnya',
  'pake',
  'suruh',
  'suruh',
  'pindah',
  'segala',
  'kek',
  'bumi',
  'miliknya',
  'saja'],
 ['uap', 'air', '?', 'sementara', 'air', 'aja', 'bln', 'ada', '5:34'],
 ['terimakasih', 'sangat', 'bermanfaat'],
 ['kesimpulannya',
  'bumi',
  'sudah',
  'mengalami',
  'beberapa',
  'kali',
  'kiamat',
  '.'],
 ['min',
  ',',
  'apakah',
  'setelah',
  'zaman',
  'kita',
  'akan',
  'ada',
  'kehidupan',
  'baru',
  'dibumi',
  'ini',
  '?'],
 ['betapa',
  'pintarnya',
  'manusia',
  'bisa',
  'membuat',
  'gambaran',
  'pembentukan',
  'bumi',
  'tapi',
  'tidak',
  'dengan',
  'kepunahan/kiamat'],
 ['tanaman', '🌳🌲🌴', 'pohon', 'tanah', '🌏'],
 ['hewan', '🐵🐔🐶🐷', 'hewan', 'bumi', '🌎'],
 ['2,5', 'juta', 'orang', '🚹', 'orang', 'penduduk😂'],
 ['2', ',', '5', 'penduduk', 'orang', '🚹', '/people'],
 ['3', 'planet', 'bumi', '🌎🌐', 'indah'],
 ['akhirnya', 'dikonoha', 'para', 'penjilat', 'bekerja'],
 ['bagi',
  'yg',
  'tdk',
  'tau',
  'tentang',
  'chenel',
  'dan',
  'adminnya',
  'mungkin',
  'percaya',
  'bagi',
  'yg',
  'tau',
  'tentang',
  'chenel',
  'ini',
  'dan',
  'admin',
  'akan',
  'tertawa',
  'bahwa',
  'yg',
  'nyata',
  'admin',
  'itu',
  'stres'],
 ['5:37',
  'jangan',
  'jangan',
  'dimasa',
  'depan',
  'pluto',
  'ada',
  'kemungkinan',
  'jadi',
  '``',
  'bumi',
  "''",
  'baru'],
 ['apakah',
  'manusia',
  'lahir',
  'sebelum',
  'bumi',
  'ada',
  'atau',
  'kah',
  'setelah',
  'bumi',
  'itu',
  'ada',
  ',',
  'manakah',
  'yang',
  'benar',
  'jika',
  'sebelum',
  'bumi',
  'ada',
  'makan',
  'sebelumnya',
  'manusia',
  'tinggal',
  'dimana',
  'dan',
  'apabila',
  'setelahnya',
  'hewan',
  'apa',
  'yang',
  'pertama',
  'ada',
  'dibumi',
  '.'],
 ['cerita', 'nggedabrus', ',', 'tau', 'tahun', 'segitu', 'dari', 'mana🤦🤦🤦'],
 ['gara',
  'gara',
  'ngonten',
  'kamu',
  ',',
  'ada',
  'yang',
  'berkomentar',
  ',',
  'lalu',
  'kamu',
  'tidak',
  'akan',
  'sadar',
  'ada',
  'kata',
  ',',
  'bahasa',
  ',',
  'tulisan',
  ',',
  'diterjemahkan',
  'lalu',
  'diperdengarkan',
  'dengan',
  'toa',
  'mesjid',
  'nurul',
  'ikhlas',
  'kelurahan',
  'cemara',
  ',',
  'lubuk',
  'pakam',
  ',',
  'deliserdang',
  ',',
  'sumatra',
  'utara',
  'dan',
  'mungkin',
  'beberapa',
  'dengan',
  'speaker',
  'aktif',
  'di',
  'rumah',
  'warga',
  'sekitar',
  ',',
  'kebisingan',
  'dan',
  'berisik',
  'dari',
  'alar',
  'alat',
  'terebut',
  'berdampak',
  'polusi',
  'udara',
  'mempercepat',
  'pemanasan',
  ',',
  'pergerakan',
  'awan',
  'yang',
  'entah',
  'dimana',
  'pasti',
  'disuatu',
  'ketika',
  'bencana',
  'bumi',
  'bagi',
  'pengguna',
  'youtube',
  'dan',
  'lainya',
  'akan',
  'terjadi',
  '.',
  'mungkin',
  'anda',
  'akan',
  'menjadi',
  'yg',
  'pertama',
  'mendapati',
  'kesakitan',
  'dan',
  'kematian',
  '.',
  'sedangkan',
  'yang',
  'lain',
  'pada',
  'hewan',
  'dan',
  'tumbuhan',
  'juga',
  '.',
  'cobalah',
  'untuk',
  'mematikan',
  'dan',
  'menghancurkan',
  'system',
  "'",
  'sound',
  'didaerah',
  'ini',
  'agar',
  'tidak',
  'ada',
  'lagi',
  'yang',
  'memperdengarkan',
  'setiap',
  'hari',
  'berulang',
  'ulang',
  'dengan',
  'toa',
  'mesjid',
  'dan',
  'speaker',
  'aktive',
  'kelewat',
  'batas',
  'ruang',
  '.',
  'bila',
  'mereka',
  'dimatikan',
  'kemudian',
  'tubuhnya',
  'secepatnya',
  'diproses',
  'dalam',
  'penggilingan',
  'pupuk',
  'dan',
  'pangan',
  'bagi',
  'tumbuhan',
  'dan',
  'hewan',
  'maka',
  'anda',
  ',',
  'pengguna',
  'youtube',
  'dan',
  'lainya',
  'di',
  'bumi',
  ',',
  'diluar',
  'angkasa',
  'pun',
  'akan',
  'menjadi',
  'tempat',
  'terindah',
  ',',
  'ternyaman',
  'bagi',
  'manusia',
  ',',
  'hewan',
  ',',
  'tumbuhan',
  ',',
  'robot',
  'di',
  'masa',
  'selanjutnya',
  '.',
  'dan',
  'saya',
  'mohon',
  'untuk',
  'tidak',
  'membagikan',
  'komentar',
  'saya',
  'ini',
  'dengan',
  'disuarakan',
  'dengan',
  'alat',
  'penggeras',
  'suara',
  'dimanapun',
  'anda',
  'berada',
  '.'],
 ['terus', 'manusianya', 'dari', 'mana'],
 ['critane', 'ora', 'genah'],
 ['ora', 'genah'],
 ['bang', '..', 'bukannya', 'manusia', 'pertama', 'itu', 'nabi', 'adam', '?'],
 ['gedabrus', '....'],
 ['bng', 'reques', '30', 'menit', 'betapa', 'mengerikan', 'kuruptor'],
 ['maha',
  'kaya',
  'allah',
  'dengan',
  'segala',
  'yang',
  'dia',
  'ciptakan',
  ',',
  'dia',
  'lah',
  'satu',
  'satunya',
  'pencipta',
  '.',
  'allah',
  'subhanahu',
  'wa',
  "ta'ala",
  'berfirman',
  ':',
  'يٰۤاَ',
  'يُّهَا',
  'النَّا',
  'سُ',
  'اعْبُدُوْا',
  'رَبَّكُمُ',
  'الَّذِيْ',
  'خَلَقَكُمْ',
  'وَا',
  'لَّذِيْنَ',
  'مِنْ',
  'قَبْلِكُمْ',
  'لَعَلَّكُمْ',
  'تَتَّقُوْنَ',
  "''",
  'wahai',
  'manusia',
  '!',
  'sembahlah',
  'tuhanmu',
  'yang',
  'telah',
  'menciptakan',
  'kamu',
  'dan',
  'orang-orang',
  'yang',
  'sebelum',
  'kamu',
  ',',
  'agar',
  'kamu',
  'bertakwa',
  '.',
  "''",
  '(',
  'qs',
  '.',
  'al-baqarah',
  '2',
  ':',
  'ayat',
  '21',
  ')'],
 ['konten',
  'keren',
  'manusia',
  'tak',
  'seberapa',
  'dibanding',
  'alam',
  'semesta',
  'ciptaan',
  'tuhan'],
 ['kira2',
  'itu',
  'semua',
  'ulah',
  'siapa',
  '...',
  'siapa',
  'yg',
  'kuasa',
  'mengatur',
  'alam',
  'semesta',
  '....'],
 ['kisah',
  'dongeng',
  'emang',
  'indah',
  '🗿🗿',
  'apalagi',
  'yang',
  'suka',
  'mendongeng',
  'tukang',
  'klaim',
  'di',
  'era',
  'digital',
  'saat',
  'ini',
  'terlebih',
  'yang',
  'baru',
  'nongol',
  'di',
  'abad',
  'ke',
  '7',
  'tapi',
  'klaim',
  'nya',
  'kemana',
  'mana',
  'berasa',
  'segala',
  'pengetahuan',
  'bersumber',
  'dari',
  'buku',
  'dongeng',
  'itu',
  'wkwk',
  '🤪🤣😂'],
 ['subhanallah',
  'walhamdullillah',
  'allahuakbar',
  'ya',
  'kita',
  'hidup',
  'ini',
  'harus',
  'saling',
  'menghargai',
  'dan',
  'menghormati',
  'dengan',
  'penuh',
  'rasa',
  'syukur',
  'kepada',
  'allah',
  'swt',
  'amiin',
  'ya',
  'allah',
  'kerena',
  'kita',
  'hambanya'],
 ['semua',
  'allah',
  'yg',
  'mengatur',
  '..',
  'allah',
  'yg',
  'membuat',
  'bumi',
  'sehingga',
  'bisa',
  'di',
  'huni',
  'mahluk',
  'hidup'],
 ['aku',
  'bangga',
  'dgn',
  'video',
  'ini',
  'sekaligus',
  'mnjd',
  'media',
  'pembejaran',
  'yg',
  'menarik',
  'untuk',
  'anak',
  "''",
  'ttg',
  'bumi'],
 ['4', 'milyar', 'thn', 'yg', 'lalu', '?', '?', 'sotoy'],
 ['lu', 'yg', 'sotoy'],
 ['kemana', 'nabi', 'adam', '?', '?'],
 ['darimana', 'dia', 'tau'],
 ['dari', 'batu🗿🗿🗿', 'serius', 'bg'],
 ['jdi',
  'penasaran',
  'klo',
  'dari',
  'segi',
  'kacamata',
  'agama',
  ',',
  'untk',
  'soal',
  'jin',
  ',',
  'pda',
  'zaman',
  'apa',
  'ya',
  'di',
  'turunkan',
  'ke',
  'bumi',
  'sebagai',
  'khalifah',
  'sebelum',
  'manusia'],
 ['ok'],
 ['masih',
  'penasaran',
  ',',
  ',',
  ',',
  'apa',
  'iya',
  'cuma',
  'galaxy',
  'kita',
  'ada',
  'kehidupan',
  '..',
  'padahal',
  'galaxy',
  'buanyak',
  'sekali',
  '.',
  'bahkan',
  'apa',
  'cuma',
  'tata',
  'surya',
  'kita',
  '...',
  'bnyak',
  'tata',
  'surya',
  'lain',
  ',',
  'apa',
  'iya',
  'gak',
  'ada',
  'kehidupan',
  '?',
  '?',
  '?'],
 ['dari', 'mana', 'tahu', 'mas', '4', 'keluar', 'tahun', 'yang', 'lalu'],
 ['p'],
 ['bang',
  'lebih',
  'mengerikan',
  'lagi',
  ',',
  'susah',
  'bgt',
  'cari',
  'kerja',
  '😭'],
 ['dinosaurus',
  'musnah',
  'karna',
  'meteor',
  '.',
  'manusia',
  'kemungkinan',
  'akan',
  'musnah',
  'karena',
  'ulahnya',
  'sendiri',
  'karena',
  'gak',
  'bisa',
  'merawat',
  'bumi',
  '🤦'],
 ['gileee'],
 ['tau', 'nya', 'kecil', 'tapi', 'kok', 'lupa', 'sm', 'allah'],
 ['yang',
  'mengerikan',
  'dari',
  'bumi',
  'merupakan',
  'makhluk',
  'yang',
  'hidup',
  'di',
  'dalam',
  'nya💀'],
 ['ada',
  'kabar',
  'baik',
  'di',
  'masa',
  'dpn',
  'akan',
  'ada',
  'damai',
  'di',
  'seluruh',
  'buminsemua',
  'orang',
  'akan',
  'saling',
  'mengasihi',
  '.',
  'kita',
  'bertetangga',
  'semua',
  'orang',
  'baik',
  'dan',
  'benar',
  ',',
  'kemana',
  'orang',
  'jahatnya',
  '?',
  'orang-orang',
  'jahat',
  'akan',
  'di',
  'musnahkan',
  ',',
  'kalau',
  'anda',
  'melihat',
  'tmpt',
  'dimana',
  'orang',
  'jahat',
  'biasa',
  'ada',
  ',',
  'tdk',
  'akan',
  'di',
  'temukan',
  'lagi',
  '.',
  'mazmur',
  '37',
  ':',
  '9',
  '-',
  '11',
  ',',
  '34',
  'amsal',
  '2',
  ':',
  '21',
  ',',
  '22',
  'orang-orang',
  'akan',
  'duduk',
  'dan',
  'aman',
  'di',
  'bawah',
  'pohon',
  'anggurnya',
  ',',
  'tdk',
  'akan',
  'ada',
  'yg',
  'membuatnya',
  'takut',
  'mikha',
  '4',
  ':',
  '4',
  '.'],
 ['wehhhh',
  '..',
  'seksssssss',
  'ruang',
  'tamu',
  'mana',
  '...',
  'bukan',
  'minta',
  'ramai',
  'pun',
  '...',
  'arwah',
  'mak',
  'dan',
  'ayah',
  'aku',
  'boleh',
  'bagi'],
 ['mantap'],
 ['kucing', 'apa'],
 ['bang', 'bikin', 'vidio', 'bumi', 'saat', 'corona'],
 ['terlalu', 'lebay', 'cvkkkkk'],
 ['dari', 'yg', 'mencipta', 'manusia', 'yg', 'merusak', 'yg', 'mencipta'],
 ['keren',
  '.',
  'hanya',
  'saja',
  'luput',
  'dari',
  'video',
  'soal',
  'penjelasan',
  'transisi',
  'dari',
  'makhluk',
  'seluler',
  'ke',
  'makhluk',
  'raksasa',
  '.'],
 ['``',
  'allaah',
  'yg',
  'menahan',
  'langit',
  'dan',
  'bumi',
  'agar',
  'tidak',
  'lenyap',
  ',',
  'dan',
  'kalau',
  'keduanya',
  'akan',
  'lenyap',
  'tidak',
  'ada',
  'yg',
  'mampu',
  'menahannya',
  'selain',
  'allaah',
  '....',
  "''",
  'allaahu',
  'akbar',
  '!'],
 ['penasaran', 'dengan', 'ajaran', 'budha', 'sampai', 'sini'],
 ['apakah',
  'kita',
  'akan',
  'punah',
  'juga',
  'dan',
  'muncul',
  'kehidupan',
  'baru',
  'lagi'],
 ['terima', 'kasih', '❤😂😂❤', 'sangat', 'terinspirasi'],
 ['ketika',
  'kita',
  'mati',
  'nanti',
  ',',
  'allah',
  'akan',
  'mengungkap',
  'kebenaran',
  'bumi',
  'yang',
  'sebenernya',
  ',',
  'bentuk',
  'nya',
  ',',
  'saat',
  'diciptakannya',
  'dll',
  ',',
  'maka',
  'tunggulah',
  'kematian',
  'mu',
  'dan',
  'kebangkitanmu',
  'nanti'],
 ['bang',
  'request',
  '30',
  'menit',
  'setelah',
  'merangsang',
  'namun',
  'hasrat',
  'tak',
  'bisa',
  'terpenuhi😢😢'],
 ['saya',
  'sngat',
  'percaya',

In [24]:
model = gensim.models.Word2Vec(sentences, min_count=1, vector_size=100, window=5, sg=0)
model.save('komen_yutub.w2v')
model = gensim.models.Word2Vec.load('komen_yutub.w2v')
w2v = model.wv
w2v.index_to_key[:10]

[',', '.', 'dan', 'bumi', 'yang', 'manusia', 'di', 'yg', '?', 'ini']

In [25]:
w2v.vectors.shape, w2v.vector_size

((8643, 100), 100)

In [26]:
w2v.similar_by_key('manusia')

[('itu', 0.9998348355293274),
 ('di', 0.9998063445091248),
 ('bumi', 0.99980229139328),
 ('bukan', 0.9997907876968384),
 ('dari', 0.9997852444648743),
 ('bahwa', 0.9997797012329102),
 ('kita', 0.9997780919075012),
 ('jadi', 0.9997727274894714),
 ('adalah', 0.9997724890708923),
 ('dan', 0.9997625946998596)]

In [27]:
def get_document_vector(tokens, model):
    valid_vectors = [model.wv[word] for word in tokens if word in model.wv]
    return np.mean(valid_vectors, axis=0)
X_features = np.array([get_document_vector(doc, model) for doc in sentences])
pd.DataFrame(X_features)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.133327,0.526053,0.221360,-0.002421,0.139350,-0.807732,0.212343,0.983513,-0.344978,-0.407514,...,0.644062,0.395263,0.178579,0.365242,0.856206,0.421450,0.350158,-0.389703,0.126599,-0.086909
1,-0.089157,0.369191,0.153323,-0.009711,0.103409,-0.566684,0.155092,0.688027,-0.250950,-0.286506,...,0.434751,0.280373,0.130096,0.264048,0.607938,0.300430,0.244178,-0.266207,0.096443,-0.061173
2,-0.106306,0.418308,0.184827,0.005418,0.119607,-0.645892,0.177920,0.787669,-0.287628,-0.328189,...,0.521488,0.306067,0.155842,0.300294,0.682673,0.336740,0.273591,-0.324990,0.105578,-0.077707
3,-0.110211,0.428646,0.188292,0.001539,0.123263,-0.665167,0.181458,0.812620,-0.290172,-0.337925,...,0.535854,0.317731,0.158092,0.304353,0.699816,0.351123,0.281316,-0.330255,0.108516,-0.079985
4,-0.131013,0.491831,0.207501,0.004950,0.132452,-0.753160,0.204222,0.921992,-0.329592,-0.382444,...,0.600721,0.368730,0.173613,0.340530,0.803392,0.397719,0.326175,-0.360550,0.122696,-0.080733
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3259,-0.003738,0.022636,0.015629,0.009236,0.010912,-0.036867,0.018718,0.050685,-0.023427,-0.012620,...,0.025442,0.028850,0.007879,0.028778,0.053010,0.018138,0.016314,-0.017377,0.001361,0.005221
3260,-0.114054,0.443476,0.185979,0.003039,0.117538,-0.682121,0.184454,0.839440,-0.297205,-0.348501,...,0.545064,0.330846,0.156859,0.306890,0.727827,0.360149,0.296750,-0.335026,0.113786,-0.077481
3261,0.001887,0.015342,0.007282,-0.006708,-0.002196,-0.028096,0.009269,0.036461,-0.003765,-0.020259,...,0.023603,0.012364,0.012407,0.012240,0.032079,0.008648,0.015705,-0.016414,0.004269,-0.002744
3262,0.009844,-0.001968,-0.008443,0.008270,0.008345,-0.005996,-0.008514,0.008647,0.000074,0.001028,...,-0.009142,-0.000853,0.004955,-0.005682,0.006314,0.002512,-0.000087,-0.005835,-0.007242,0.009431
3263,-0.024715,0.101526,0.043834,-0.005535,0.025200,-0.151287,0.045963,0.184497,-0.066198,-0.073369,...,0.122519,0.074236,0.036752,0.073199,0.159755,0.075306,0.064559,-0.074849,0.019759,-0.020665

In [28]:
X = UMAP().fit_transform(w2v.vectors)

df2 = pd.DataFrame(X, columns=['umap1', 'umap2'])
df2['word'] = w2v.index_to_key

fig = px.scatter(df2, x='umap1', y='umap2', text='word')
fig.update_traces(textposition='top center')
fig.update_layout(height = 800,
                  title_text = 'Word2Vec Visualization')
fig.show()

In [29]:
model_fasttext = gensim.models.FastText(sentences, min_count=1,
                                        vector_size=100, window=5,
                                        min_n=3, max_n=6,
                                        sg=1, epochs=10)
model_fasttext.save('komen_yutub.fasttext')
model_fasttext = gensim.models.Word2Vec.load('komen_yutub.fasttext')
fasttext = model_fasttext.wv
fasttext.index_to_key[:10]

[',', '.', 'dan', 'bumi', 'yang', 'manusia', 'di', 'yg', '?', 'ini']

In [30]:
fasttext.vectors.shape

(8643, 100)

In [31]:
fasttext.similar_by_key('bumi')

[('.bumi', 0.9972699880599976),
 ('❤❤bumi❤', 0.9717328548431396),
 ('bumi.🙏', 0.9712210893630981),
 ('bumi🥲', 0.9698246717453003),
 ('kebumi', 0.9694671630859375),
 ('bumi❤', 0.9693486094474792),
 ('bumi😌', 0.968495786190033),
 ('bumi.', 0.9668769240379333),
 ('bumii😮', 0.9658671617507935),
 ('bumi😂', 0.9648703336715698)]

In [32]:
def get_document_vector(tokens, model):
    valid_vectors = [model.wv[word] for word in tokens if word in model.wv]
    # if not valid_vectors:
    #   return np.zeros(model.vector_size)
    return np.mean(valid_vectors, axis=0)
X_features = np.array([get_document_vector(doc, model_fasttext) for doc in sentences])
pd.DataFrame(X_features)

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
0,-0.316598,-0.199163,0.034255,0.315062,0.510571,-0.249582,0.428488,0.084103,-0.115517,-0.416921,...,0.049579,0.183954,-0.214284,0.056865,-0.293273,0.235163,-0.371015,-0.162072,-0.135570,0.488101
1,-0.367314,-0.149185,0.109378,0.338803,0.310942,-0.358531,0.576675,0.040002,-0.154079,-0.297011,...,-0.039912,0.093485,-0.019373,-0.039259,-0.283167,0.189134,-0.241754,-0.139143,0.080991,0.660321
2,-0.271132,-0.250801,0.192503,0.210944,0.410465,-0.312220,0.259358,0.090064,-0.218726,-0.366663,...,-0.006616,-0.030830,0.011816,-0.006015,-0.340994,0.048753,-0.318416,-0.341752,-0.097138,0.417673
3,-0.335599,-0.272516,0.237131,0.258174,0.404380,-0.275049,0.371137,0.076507,-0.204855,-0.399021,...,0.054899,0.015007,-0.028567,-0.037979,-0.330119,0.125452,-0.365358,-0.370583,-0.135911,0.414472
4,-0.362827,-0.236749,0.019864,0.354177,0.445670,-0.220443,0.382630,0.077953,-0.146793,-0.390802,...,-0.015796,0.131039,-0.178128,-0.024492,-0.351268,0.191707,-0.339556,-0.223287,-0.139971,0.450762
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3259,-0.228368,-0.081056,0.071183,0.160062,0.350859,-0.163037,0.419857,0.044374,-0.077546,-0.344573,...,0.003219,0.091621,-0.112530,-0.063924,-0.239078,0.210341,-0.270702,-0.110270,-0.089724,0.396312
3260,-0.364681,-0.201442,0.115692,0.285109,0.348626,-0.216525,0.522827,0.103179,-0.187330,-0.465083,...,0.033662,0.118832,-0.169362,-0.034143,-0.271725,0.254818,-0.347873,-0.275283,-0.130373,0.514504
3261,-0.150319,-0.093293,0.108975,0.122432,0.224535,-0.150248,0.329914,0.032693,-0.120629,-0.206199,...,-0.001858,-0.032718,0.001558,-0.038682,-0.175795,0.133102,-0.218157,-0.161564,-0.022675,0.290788
3262,-0.147560,-0.066200,0.028747,0.108281,0.121798,-0.057609,0.134454,0.011486,-0.067181,-0.128539,...,0.032273,0.045267,-0.071221,0.017525,-0.127805,0.075327,-0.088833,-0.071076,-0.031636,0.145190
3263,-0.185107,-0.080916,0.139291,0.083070,0.280309,-0.207421,0.477696,0.124627,-0.211500,-0.314294,...,-0.039475,-0.053919,0.034059,-0.069257,-0.259568,0.165530,-0.269724,-0.290590,0.018394,0.416853

In [33]:
X = UMAP().fit_transform(fasttext.vectors)

df2 = pd.DataFrame(X, columns=['umap1', 'umap2'])
df2['word'] = fasttext.index_to_key

fig = px.scatter(df2, x='umap1', y='umap2', text='word')
fig.update_traces(textposition='top center')
fig.update_layout(height = 800,
                  title_text = 'fasttext Visualization')
fig.show()